AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - "bin/**/*"
  - "spec/rails_helper.rb"
  - "config/environments/production.rb"
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
  
